"""initial schema

Revision ID: 1ef1a5f0bbd0
Revises: e9f52b97f0c2
Create Date: 2025-10-25 11:49:05.059321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef1a5f0bbd0'
down_revision: Union[str, None] = 'e9f52b97f0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_analysis_id', table_name='legal_analysis')
    op.drop_table('legal_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='legal_analysis_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='legal_analysis_pkey')
    )
    op.create_index('ix_legal_analysis_id', 'legal_analysis', ['id'], unique=False)
    # ### end Alembic commands ###
