"""create_pneumonia_cases_table

Revision ID: 352e6bf29cb0
Revises: 807206a73b3e
Create Date: 2025-09-28 17:44:10.625143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352e6bf29cb0'
down_revision: Union[str, None] = '807206a73b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pneumonia_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer, nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pneumonia_cases')
    # ### end Alembic commands ###
