"""create insurance_claims table

Revision ID: 7a0307f1629d
Revises: 4f3f07ca5a5e
Create Date: 2025-09-26 02:55:57.578998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0307f1629d'
down_revision: Union[str, None] = '4f3f07ca5a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Provider', sa.String(), nullable=False),
    sa.Column('PotentialFraud', sa.String(), nullable=False),
    sa.Column('Fraud_Probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_id'), 'insurance_claims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_claims_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    # ### end Alembic commands ###
