"""add created_at column to legal_cases

Revision ID: 80485d652809
Revises: ff6baace62ad
Create Date: 2025-11-11 16:33:33.615673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80485d652809'
down_revision: Union[str, None] = 'ff6baace62ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_cases_id'), table_name='legal_cases')
    op.drop_table('legal_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('legal_issues', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relevant_laws', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('legal_cases_pkey'))
    )
    op.create_index(op.f('ix_legal_cases_id'), 'legal_cases', ['id'], unique=False)
    # ### end Alembic commands ###
