"""Create pneumonia_cases table

Revision ID: 807206a73b3e
Revises: e31a478eb6ae
Create Date: 2025-09-28 15:15:51.492166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807206a73b3e'
down_revision: Union[str, None] = 'e31a478eb6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
