"""update legal_analysis table 

Revision ID: a50a2bf2be61
Revises: e30703ce9b8d
Create Date: 2025-11-12 01:13:21.681389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50a2bf2be61'
down_revision: Union[str, None] = 'e30703ce9b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_cases', sa.Column('top_issue', sa.Text(), nullable=True))
    op.add_column('legal_cases', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.drop_column('legal_cases', 'relevant_laws')
    op.drop_column('legal_cases', 'result_json')
    op.drop_column('legal_cases', 'legal_issues')
    op.drop_column('legal_cases', 'input_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_cases', sa.Column('input_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legal_cases', sa.Column('legal_issues', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legal_cases', sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legal_cases', sa.Column('relevant_laws', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('legal_cases', 'confidence_score')
    op.drop_column('legal_cases', 'top_issue')
    # ### end Alembic commands ###
