"""Add foreign key to LegalCase

Revision ID: b2e513d57bc6
Revises: 52d0f756022b
Create Date: 2025-10-27 00:31:39.835075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2e513d57bc6'
down_revision: Union[str, None] = '52d0f756022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('legal_issues', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('relevant_laws', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='legal_cases_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='legal_cases_pkey')
    )
    # ### end Alembic commands ###
