"""add is_admin to users

Revision ID: d564a744cd41
Revises: 80485d652809
Create Date: 2025-11-11 20:36:30.447454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd564a744cd41'
down_revision: Union[str, None] = '80485d652809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_cases_id', table_name='legal_cases')
    op.drop_table('legal_cases')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.create_table('legal_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('legal_issues', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relevant_laws', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='legal_cases_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='legal_cases_pkey')
    )
    op.create_index('ix_legal_cases_id', 'legal_cases', ['id'], unique=False)
    # ### end Alembic commands ###
