"""create pneumonia_cases table

Revision ID: e31a478eb6ae
Revises: 3c2c83ceac22
Create Date: 2025-09-28 11:38:00.210329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31a478eb6ae'
down_revision: Union[str, None] = '3c2c83ceac22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
